simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.PostCreate.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<str:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<str:pk>/', views.PostDelete.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login_redirect/', views.LoginRedirectPage.as_view(), name='login_redirect'),
    path('logout_redirect/', views.LogoutRedirectPage.as_view(), name='logout_redirect'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
]

simplesocial/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

import misaka

from groups.models import Group


# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=255, blank=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.message
        
    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.user.username, 'pk':self.pk})
        
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'title']
        
        
        

simplesocial/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages

from django.http import Http404
from django.views.generic import ListView, TemplateView, DetailView, DeleteView, CreateView

from braces.views import SelectRelatedMixin

from .models import Post
from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.
class PostList(SelectRelatedMixin, ListView):
    model = Post
    select_related = ('user', 'group')

class UserPosts(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'
    
    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
                
        return context
        
class PostDetail(SelectRelatedMixin, DetailView):
    model = Post
    select_related = ('user', 'group')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))
        

class PostCreate(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    fields = ('title', 'message', 'group')
    model = Post
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        
        return super().form_valid(form)
        
class PostDelete(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')
    
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id__exact=self.request.user.id)
        
    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)
    
    
    
    
    
    
    
            
            
            

simplesocial/posts/templates/posts/_post.html
<div class="post media">
  <div class="media-body">
    <h5 class="media-heading">
      <h3>{{post.title|safe}}</h3>
      <span class="username">
        <a href="{% url 'posts:for_user' username=post.user.username %}">
          @{{post.user.username}}
        </a>
      </span>
      <time class="time">
        <a href="{% url 'posts:single' username=post.user.username pk=post.pk% }">
          {{post.created_at}}
        </a>
      </time>
    </h5>
    
    <div class="media-footer">
      {% if user.is_authenticated and post.user == user %}
        <a href="{% url 'posts:delete' pk=post.pk %}" class="btn btn-warning">
          <span class="glyphicon glyphicon-remove text-danger"></span>
          <span class="text-danger icon-label">Delete</span>
        </a>
      {% endif %}
    </div>
    
    
  </div>
</div>

simplesocial/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
  <div class="posts-page">
    <div class="container">
      {% block pre_post %}{% endblock %}
      {% block post_content %}{% endblock %}
      {% block post_detail %}{% endblock %}
      
    </div>
  </div>
  
{% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  
  <h3>Are you sure you want to delete this post?</h3>
  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>
    
    <form class="" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Confirm Delete" class="btn btn-danger btn-lg">
      <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-secondary btn-lg">
        Cancel
      </a>
    </form>
    
  
{% endblock %}

simplesocial/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  
  <div class="col-md-8">
    {% include "posts/_post.html" %}
  </div>
  
{% endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}

{% block post_content %}

  <form class="" action="{% url 'posts:create' %}" method="post" id="post-form">
    {% csrf_token %}
    
    {% bootstrap_form form %}
    <input type="submit" name="" value="Submit" class="btn btn-success btn-large">
    
  </form>
  
{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post %}
  <div class="col-md-4">
    {% if request.user.is_authenticated %}
      <div class="card card-with-shadow">
        <div class="content">
          <h5 class="title">Your Groups</h5>
          <ul class="list-unstyled">
            {% for member_group in  get_user_groups %}
              <li class="group li-with-bullet">
                <a href="{% url 'groups:single' slug=member_group.group.slug %}">
                  {{member_group.group.name}}
                </a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    
    {% endif %}
    
    <div class="card card-with-shadow">
      <div class="content">
        <h5 class="title">All Groups</h5>
        <ul class="list-unstyled">
          {% for other_group in get_other_groups %}
            <li class="group li-with-bullet">
              <a href="{% url 'groups:single' slug=other_group.slug %}">
                {{other_group.name}}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
    
    
  </div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
    
  </div>
{% endblock %}

simplesocial/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}





{% block pre_post %}
  <div class="col-md-4">
    <h1>@{{post_user}}</h1>
  </div>
  <hr>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>
{% endblock %}